name: dagger
on:
  push:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dagger build
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          # assumes a Go project
          # modify to use different function(s) as needed
          # module: github.com/kpenfound/dagger-modules/golang@v0.2.0
          args: build --source=.
          # assumes the Dagger Cloud token is in
          # a repository secret named DAGGER_CLOUD_TOKEN
          # set via the GitHub UI/CLI
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Dagger test
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          args: test --source=.
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Make call to different module
        uses: dagger/dagger-for-github@v5
        with:
          version: "latest"
          verb: call
          module: github.com/shykes/daggerverse/hello
          args: hello --greeting Helloooo --name egg
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}